# Use the official Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY app.py /app/app.py

# Set the entrypoint to the Python script
ENTRYPOINT ["python", "app.py"]

