#https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

apiVersion: v1
kind: Namespace
metadata:
  name: v6-node

---
apiVersion: v1
kind: Namespace
metadata:
  name: v6-jobs

---

kind: NetworkPolicy # Policy to disable job's networking, except with the Node
apiVersion: networking.k8s.io/v1
metadata:
  name: v6-jobs-allow-egress-to-node-proxy-only
  namespace: v6-jobs
spec:
  podSelector: {} # This selects all pods in the v6-jobs namespace
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: v6-node-pod
          kubernetes.io/metadata.namespace: v6-node 
    ports:
    - protocol: TCP
      port:  4567 # Port exposed by default by the Node's server proxy
  - to:
    - namespaceSelector: {} # allow only the use DNS within the cluster
    ports:
    - protocol: UDP #This enables internal DNS resolution (otherwhise the static IP addresses of the proxy should be given)
      port: 53

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy #network policy to allow outbound traffic from the node
metadata:
  name: v6-proxy-allow-internet-egress
  namespace: v6-node
spec:
  podSelector:
    matchLabels:
      app: v6-node-pod
  policyTypes:
  - Egress
  egress:
  - {} # This rule allows egress traffic to any destination (could be restricted to the V6-server only)





