name: Build and push a docker image of the v6 (k8s) node

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Create named builder
      run: docker buildx create --name mybuilder
      
    - name: Use created builder
      run: docker buildx use mybuilder
      
    - name: Inspect bootstrap state
      run: docker buildx inspect --bootstrap
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: ./integration-poc
        push: true
        platforms: linux/arm64,linux/amd64
        tags: hcadavidescience/v6_k8s_node:latest
