name: Build and Push Multi-Architecture Image

on:
  push:
    branches: [ hcadavid-ghaction ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push multiarch image
        uses: docker/build-push-action@v3
        with:
          context: ./integration_poc
          platforms: linux/arm64,linux/amd64
          push: true
          tags: hcadavidescience/v6_k8s_node:latest
